Map css + added extension file
QuantStack/ipyopenlayers pull request #14
Opened 2024-06-19 14:13 UTC by Nour-Cheour10

2024-06-19 14:26 UTC, martinRenou approved these changes
Thanks!

2024-06-19 14:27 UTC, martinRenou commented
Bot update galata references

2024-06-19 14:46 UTC, martinRenou commented
It looks like your PR breaks the visual regression test: [the map used to render but it does not anymore](https://github.com/QuantStack/ipyopenlayers/pull/14/commits/c22b4e0d0d11505290faf362b4dfdf442ef2a464#diff-80806acadc25a21ee4285368ccb73ddfed3efbeeb5046dc978bc62b5fd27ac4f)

2024-06-20 07:52 UTC, martinRenou requested changes

2024-06-20 07:52 UTC, martinRenou commented on package-lock.json
This looks wrong. It seems you have a `package-lock.json` because you probably ran `npm` locally instead of `jlpm`.

This file should not be commited and put into the `.gitignore`

2024-06-20 09:34 UTC, Nour-Cheour10 commented on package-lock.json
Thank you, done.

2024-06-20 17:17 UTC, closed without merging