Vector layer
QuantStack/ipyopenlayers pull request #26
Opened 2024-07-18 12:09 UTC by Nour-Cheour10

2024-07-19 10:27 UTC, Nour-Cheour10 commented
update galata references

2024-07-19 12:00 UTC, Nour-Cheour10 commented
Bot update galata references

2024-07-19 13:18 UTC, Nour-Cheour10 commented
update galata references

2024-07-19 13:45 UTC, martinRenou commented
please update snapshots!!!

2024-07-24 08:11 UTC, martinRenou commented
This is conflicting with the main branch, you'd need to rebase

2024-07-24 10:17 UTC, Nour-Cheour10 commented
please update snapshots

2024-07-24 11:30 UTC, martinRenou commented
Triggering CI

2024-07-24 13:49 UTC, Nour-Cheour10 commented
please update snapshots

2024-07-24 14:25 UTC, martinRenou commented
Triggering CI

2024-07-24 15:19 UTC, martinRenou commented on package.json
> +    "dotenv": "^16.4.5",
Do you need this?

2024-07-24 15:21 UTC, Nour-Cheour10 commented on package.json
> +    "dotenv": "^16.4.5",
no I'll take it off

2024-07-25 09:55 UTC, Nour-Cheour10 commented
please update snapshots

2024-07-25 10:14 UTC, Nour-Cheour10 commented
please update snapshots

2024-07-25 13:02 UTC, martinRenou commented
Triggering CI

2024-07-26 08:16 UTC, martinRenou requested changes

2024-07-26 08:16 UTC, martinRenou commented on examples/example-data.json
This file is quite big, and I don't see it being used in your notebooks, should we remove them from the repository?

2024-07-26 13:03 UTC, martinRenou approved these changes
Thanks!

2024-07-26 13:03 UTC, merged